[build]
  base = "frontend/"
  publish = "frontend/dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirect rules for SPA
[[redirects]]
  from = "/api/*"
  to = "https://okaygoal-backend.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws"
  to = "https://okaygoal-backend.railway.app/ws"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https: wss:; font-src 'self' data:;"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

# Environment variables (set these in Netlify UI)
# VITE_API_URL = "https://okaygoal-backend.railway.app/api/v1"
# VITE_WS_URL = "wss://okaygoal-backend.railway.app/ws"